### PR TITLE
Many improvements and compatibility with HogBaySoftware's TaskPaper

### PR DESCRIPTION
**Pull request by anyakichi**
I've done many improvements and bug fixes to taskpaper.vim.
- Add useful functions for users to define his own mappings easily
  - Add, delete, toggle, and update tags
  - Go previous or next project
  - Move projects, tasks and notes to another project
  - Search for keywords or tags with regexp
- More compatible with HogBaySoftware's TaskPaper
  - Tag to projects and notes not only tasks
  - Shortcut to @today tag
  - Archiving done support
- Multi-level folding of projects work perfectly
- Add a new feature to fold only notes

Pull up whole or partial changes you prefer.
I've changed almost all code...

### CODE REVIEW

**Comment by nshram** [comment]
Wooowww! Hey man! This is unbelievable!

**Comment by nshram** [comment]
The vim after file needs to be added? (~/.vim/after/plugin/taskpaper.vim). This was there in the original. This maps carriage return to create new todo entry (with a tab, hyphen and space). Was added by https://github.com/msutherl/taskpaper.vim

**Comment by nshram** [comment]
How do you "Move projects, tasks and notes to another project"? Don't see any shortcut for it.

**Comment by anyakichi** [comment]
I deleted mappings to carriage return because it is buggy.
I've just added alternative mappings instead. Pull my master and write this in your vimrc:

<pre>
augroup vimrc-taskpaper
    autocmd!
    autocmd FileType taskpaper
    \   nmap &lt;buffer&gt; o &lt;Plug&gt;TaskPaperNewline
    \|  imap &lt;buffer&gt; &lt;CR&gt; &lt;Plug&gt;TaskPaperNewline
augroup END
</pre>


I have not added them by default to avoid destroying user's mappings.

No shortcut for moving items though this function is used to archive done items internally.
You can create your own shortcut like this:

<pre>
nnoremap &lt;buffer&gt; &lt;Leader&gt;tm :&lt;C-u&gt; call taskpaper#move(['Project', 'Sub project'])&lt;CR&gt;
</pre>

**Comment by davidoc** [comment]
Hey, this looks great! I'll take a look this evening.

**Comment by nshram** [comment]
\ta not working. It should unfold all folds. doesn't. zo works, but have to use it several times. \ta works ok in David's last version.

**Comment by anyakichi** [comment]
Use zR simply or map \ta to zR by yourself.

**Comment by nshram** [comment]
Thanks! zR or even zr works. Maybe the docs should be updated? Great effort on your part to really supercharge this plugin!

**Comment by davidoc** [comment]
On 15/02/12 08:03, nshram wrote:

> Thanks! zR or even zr works. Maybe the docs should be updated? Great effort on your part to really supercharge this plugin!

I've merged this (still have to push it). One of the things already on my
todo list is to include zR and other (un)fold commands in the documentation.

David

## 

Ánra Taighde - Scoil na hEolaíochta Ríomhaireachta ⁊ na Staitisticí,
 Coláiste na Tríonóide, Baile Átha Cliath, BÁC 2
Research Fellow - School of Computer Science & Statistics,
 Trinity College Dublin, Dublin 2                    T: +353 1 896 1720

**Comment by anyakichi** [comment]
＞ I've merged this (still have to push it).

Thanks!

I've updated the document.  Fixed obsolete description and added the "customize" section.

**Comment by nshram** [comment]
Generally all the folding/unfolding commands are working only with top level projects. How to make them work for sub-projects while leaving the parent projects as is? For example, the \tP command for focusing on a project doesn't work for sub-projects: the parent project too is unfolded. It's possible to unfold a parent project while keeping the sub-project folded by using \tp followed by zo. But not vice-versa: you can't unfold a sub-project while keeping (other parts of) the parent project folded.

At a more general level, I think additional commands to fold/unfold lines purely based on indentation levels would be useful. In such a case it wouldn't matter if the parent were a project, task or note.

**Comment by anyakichi** [comment]
Why \tP doesn't work for sub-projects is that I did so because I think this behavior is useful.
You can focus on a sub-project if you modify ftplugin/taskpaper.vim like:

<pre>
- \       :<C-u>call taskpaper#fold_projects()<CR>zO
+ \       :<C-u>call taskpaper#fold_projects()<CR>99zo
</pre>


But I will fix this because the latter behavior is close to  HogBaySoftware's TaskPaper.

Try ":set foldmethod=indent" then "zM" if you fold lines based on indentation.

**Comment by nshram** [comment]
Hello anyakichi! Tested your latest changes:
1. \tP now focuses on sub-projects, but any tasks at the same level are also visible!
2. \tg works only for top level projects. can't use it for moving to sub-projects

## Test file used for both 1. and 2. as below:
- Task0
  Proj1:
  <tab>\- Task1
  <tab>\- Task1a
  <tab>Proj2:
  <tab><tab>\- Task2
  <tab><tab>\- Task3
  <tab>\- Task3a
  <tab>\- Task3b
  <tab>Proj2a:
  <tab><tab>\- Task2a 
  <tab><tab>\- Task2b
  <tab>\- Task3c
  <tab>\- Task3d
  <tab>Proj2b:
  <tab><tab>\- Task2c 
  <tab><tab>\- Task2d
  <tab>\- Task3e
  <tab>\- Task3f
- Task0a
- Task0b
  Proj3:
  <tab>\- Task4
  <tab>\- Task5
- Task0c

## \- Task0d

**Comment by nshram** [comment]
Sorry! Test file formatting screwed up. Should be like:
- Task0
  Proj1:
  tab- Task1
  tab- Task1a
  tabProj2:
  tabtab- Task2
  tabtab- Task3
  tab- Task3a
  tab- Task3b
  tabProj2a:
  tabtab- Task2a 
  tabtab- Task2b
  tab- Task3c
  tab- Task3d
  tabProj2b:
  tabtab- Task2c 
  tabtab- Task2d
  tab- Task3e
  tab- Task3f
- Task0a
- Task0b
  Proj3:
  tab- Task4
  tab- Task5
- Task0c
- Task0d

**Comment by anyakichi** [comment]
> \tP now focuses on sub-projects, but any tasks at the same level are also visible!

Oh, I've understood what you mean.
The current behavior doesn't truly focus on a project as you say.
I will fix it.

> \tg works only for top level projects. can't use it for moving to sub-projects

Type "Proj1:Proj2" to go to the Proj2 on prompt.
You can complete a project name with tab.

**Comment by nshram** [comment]
Sorry again! \tg _**does**_ work in moving to a sub-project. But only by entering tab continuously till the sub-project you want shows up. **Or** by typing the project name like "main project:sub-project". I had tried typing the sub-project name directly without the parent project's name.

Again, great work!

**Comment by anyakichi** [comment]
I'm sorry.  I assumed "set wildmenu=list:longest,full" environment.
You can see a completion list with &lt;C-d&gt;, too.
And you can complete a project name with regexp like ".*Proj2&lt;Tab&gt;" on my master.

**Comment by davidoc** [comment]
I've merged anyakichi's current master and pushed to my master.

**Pull request merged**
