### PR TITLE
Always use tabs instead of spaces

### PR DESCRIPTION
**Pull request by adrianocastro**
Taskpaper uses tabs instead of spaces for nesting. I've added a line to ftdetect/taskpaper.vim so it sets noexpandtab for taskpaper files. I've also added taskpaper detection for *.todo files.

### CODE REVIEW

**Comment by davidoc** [comment]
Thanks, I'll accept the tabs-not-spaces change. I'm inclined to reject the `*.todo` change, as this is a personal choice (or does TaskPaper open `*.todo` files by default?)

**Comment by adrianocastro** [comment]
Hi David,

TaskPaper also opens *.todo files by default. Might want to merge that too.

Cheers,
Adriano

**Comment by davidoc** [comment]
Are you sure? It doesn't seem to be configured like that on my Mac.

**Comment by adrianocastro** [comment]
After further testing it would appear the .todo extension isn't registered. If the file is created with TaskPaper then yes, the .todo extension works. That said if you save the file straight from TaskPaper without an extension that works too. Not really sure how that is done because no special headers or anything is added to the file as far as I can tell.

I suppose I was under the impression that it worked because I tend to save all my TaskPaper files as .todo and because I've either created in TaskPaper or opened with the app they all worked perfectly.

I'd put this down to personal preference but it's definitely something I quite like. The .taskpaper extension just seems to long to me and somewhat limited. I have .todo files from way before TP and because TP syntax is so simple, most of them didn't even need updating to work properly.

**Comment by adrianocastro** [comment]
FWIW I've asked on the official [TaskPaper forums](http://groups.google.com/group/taskpaper) if they'd consider registering the .todo extension under TaskPaper. Because I'm a new member my question is being moderated for now.

**Pull request merged**
