### PR TITLE
:Tag command, Syntax Updates, and ShowProject function

### PR DESCRIPTION
**Pull request by mattsacks**
Hey there - really like taskpaper.vim! I made some changes and fixes that I thought would make it a bit more awesome.
- Use `:Tag` for adding/removing tags.
- `<Leader>tp` for showing projects (from wherever a cursor is inside the project)
- Syntax fixes for `@done` tags and not requiring Projects to have a blank line under them
- `echomsg` to make _done!_ messages stick

Cheers!

### CODE REVIEW

**Comment by mattsacks** [comment]
Ping. Any update on getting this pulled in?

**Comment by davidoc** [comment]
Hi, working backwards through some of the issues and pull requests. I'll be merging this soon.

**Comment by mattsacks** [comment]
Glad you're back - let me know if you have any questions / comments on what I've changed.

**Comment by davidoc** [comment]
...and after merging some other changes I lost some of this functionality. I've added Issue #33 to track this

**Pull request merged**
