### PR TITLE
don't show invisible characters

### PR DESCRIPTION
**Pull request by spikegrobstein**
When the user has `set list`, this should be disabled in .taskpaper files.

### CODE REVIEW

**Comment by davidoc** [comment]
Hi Spike, thanks for the pull request.

I'm open to persuasion, but isn't this a personal decision? If someone has `set list` they may want and expect it for all files.

If you want to selectively disable `set list` for .taskpaper files you could modify the `au!` line in `ftdetect/taskpaper.vim` to specify `set nolist`.

**Comment by spikegrobstein** [comment]
you're 100% correct. I misunderstood how that configuration options works, so I screwed that up (I'm a bit of a vimscript/config n00b at the moment). My current fix is a file in `~/.vim/after/ftplugin/taskpaper.vim` that specifically calls `set nolist`.

My initial test of the pullrequest appeared to work, but I didn't think to test opening a file of a different type.

With that said, would you recommend that I make your suggested change or would you rather accept this as a feature request and make the change?

**Comment by davidoc** [comment]
I think you should make this as a personal configuration change. If that's OK, I'll close this request.

**Comment by spikegrobstein** [comment]
Understandable. Thanks for the consideration!

**Pull request closed without merging**
